### PR TITLE
[GEP-26] Add support for credentials binding

### PR DESCRIPTION
**Pull request by dimityrmirchev**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/9586

**Special notes for your reviewer**:

**Release note**:

```feature user
Cloud provider credentials can now be extracted following a shoot reference to a credentials binding.
```

### CODE REVIEW

**Review by petersutter — APPROVED** [review]
thank you for the contribution!

/lgtm

**Review by holgerkoser — APPROVED** [review]
/lgtm

**Comment by dimityrmirchev** [comment]
I rebased in order to include the latest version of the main branch. Not sure if this was necessary, but github was pushing me in that direction 
image

**Review by petersutter — APPROVED** [review]
/lgtm

**Pull request merged**
