### PR TITLE
change signature options

### PR DESCRIPTION
**Pull request by tedteng**
**What this PR does / why we need it**:
change  signature options style 
https://github.com/gardener/gardenctl-v2/pull/162#discussion_r1005591642
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other developer

```

### CODE REVIEW

**Review by petersutter — APPROVED** [review]
/lgtm

**Comment by tedteng** [comment]
rebased, I don't have merge permission feel free to merge the PR Thanks

**Review by grolu — APPROVED** [review]
/lgtm

**Review by holgerkoser — APPROVED** [review]
/lgtm

**Comment by tedteng** [comment]
PR rebased, Please merge the PR, I don't have permission to merge it, Thanks. @gardener/gardenctl-v2-maintainers
image

**Pull request merged**
